---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# UMIcountR

<!-- badges: start -->
<!-- badges: end -->


## Installation

#You can install the released version of UMIcountR from [CRAN](https://CRAN.R-project.org) with:

#``` r
#install.packages("UMIcountR")
#```

You can install UMIcountR from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("cziegenhain/UMIcountR")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(UMIcountR)
## basic example code
#load reads from the provided example bam file (Smart-seq3 data)
bam_path <- system.file("extdata", "Smartseq3.TTACCTGCCAGATTCG.bam", package = "UMIcountR", mustWork = TRUE)
spikedat <- extract_spike_dat(bam_path, match_seq_before_UMI = "GAGCCTGGGGGAACAGGTAGG", match_seq_after_UMI = "CTCGGAGGAGAAA")
```

After loading the data, we can see the data structure: 
```{r spikedat}
str(spikedat)
```


Next, we can run the filtering for overrespresented spUMIs:
```{r pressure, echo = FALSE}
overrep <- get_overrepresented_spikes(spikedat, readcutoff = 75)
overrep$plots[[1]]
```
